spring.application.name=calculadora-emprestimos
spring.datasource.url=jdbc:h2:mem:calculadora_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# Debug / request logging
# Enable Spring Boot debug logging (optional, high verbosity)
debug=true

# Specific log levels to help tracing requests and application flow
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.filter=DEBUG
logging.level.com.softwmicro=DEBUG
logging.level.org.hibernate.SQL=DEBUG


